import { Metadata } from 'next';
import './globals.css';
import MuiContext from '@/context/MuiContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'initial-scale=1, width=device-width',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MuiContext>{children}</MuiContext>
      </body>
    </html>
  );
}
